[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
description = "Development-related Tasks"
publish = false

[dependencies]
khonsu-tools = { git = "https://github.com/khonsulabs/khonsu-tools.git", branch = "main" }
